In [1]:
# Dependencies
import pandas as pd
import numpy as np

In [2]:
# Name of the CSV file
file = 'Resources/player.csv'

In [3]:
# The correct encoding must be used to read the CSV in pandas
df = pd.read_csv(file)
print(df)

       player_id  birth_year  birth_month  birth_day birth_country  \
0      aardsda01      1981.0         12.0       27.0           USA
1      aaronha01      1934.0          2.0        5.0           USA
2      aaronto01      1939.0          8.0        5.0           USA
3       aasedo01      1954.0          9.0        8.0           USA
4       abadan01      1972.0          8.0       25.0           USA
5       abadfe01      1985.0         12.0       17.0          D.R.
6      abadijo01      1854.0         11.0        4.0           USA
7      abbated01      1877.0          4.0       15.0           USA
8      abbeybe01      1869.0         11.0       11.0           USA
9      abbeych01      1866.0         10.0       14.0           USA
10     abbotda01      1862.0          3.0       16.0           USA
11     abbotfr01      1874.0         10.0       22.0           USA
12     abbotgl01      1951.0          2.0       16.0           USA
13     abbotje01      1972.0          8.0       17.0           USA
14     abbotji01      1967.0          9.0       19.0           USA
15     abbotku01      1969.0          6.0        2.0           USA
16     abbotky01      1968.0          2.0       18.0           USA
17     abbotod01      1888.0          9.0        5.0           USA
18     abbotpa01      1967.0          9.0       15.0           USA
19      aberal01      1927.0          7.0       31.0           USA
20     abercda01      1850.0          1.0        2.0           USA
21     abercre01      1980.0          7.0       15.0           USA
22     abernbi01      1929.0          1.0       30.0           USA
23     abernbr01      1977.0          9.0       23.0           USA
24     abernte01      1921.0         10.0       30.0           USA
25     abernte02      1933.0          3.0        6.0           USA
26     abernwo01      1915.0          2.0        1.0           USA
27     aberscl01      1921.0          8.0       28.0           USA
28     ablesha01      1883.0         10.0        4.0           USA
29     abnersh01      1966.0          6.0       17.0           USA
...          ...         ...          ...        ...           ...
18816  zimmejo02      1986.0          5.0       23.0           USA
18817  zimmero01      1916.0          9.0       13.0           USA
18818  zimmery01      1984.0          9.0       28.0           USA
18819   zinkch01      1979.0          8.0       26.0           USA
18820   zinkwa01      1898.0         11.0       21.0           USA
18821   zinnfr01      1865.0         12.0       21.0           USA
18822   zinngu01      1887.0          2.0       13.0           USA
18823   zinnji01      1895.0          1.0       21.0           USA
18824  zinsebi01      1918.0          1.0        6.0           USA
18825  zinteal01      1968.0          5.0       19.0           USA
18826  zipfebu01      1938.0         11.0       18.0           USA
18827   ziskri01      1949.0          2.0        6.0           USA
18828   zitoba01      1978.0          5.0       13.0           USA
18829  zitzmbi01      1895.0         11.0       19.0           USA
18830  zmiched01      1884.0         10.0        1.0           USA
18831  zobribe01      1981.0          5.0       26.0           USA
18832  zoccope01      1977.0          2.0        6.0           USA
18833  zoldasa01      1918.0         12.0        8.0           USA
18834  zoskyed01      1968.0          2.0       10.0           USA
18835  zuberbi01      1913.0          3.0       26.0           USA
18836  zuberjo01      1969.0         12.0       10.0           USA
18837  zuletju01      1975.0          3.0       28.0        Panama
18838  zumayjo01      1984.0         11.0        9.0           USA
18839  zuninmi01      1991.0          3.0       25.0           USA
18840  zupcibo01      1966.0          8.0       18.0           USA
18841   zupofr01      1939.0          8.0       29.0           USA
18842  zuvelpa01      1958.0         10.0       31.0           USA
18843  zuverge01      1924.0          8.0       20.0           USA
18844  zwilldu01      1888.0         11.0        2.0           USA
18845   zychto01      1990.0          8.0        7.0           USA

      birth_state        birth_city  death_year  death_month  death_day  \
0              CO            Denver         NaN          NaN        NaN
1              AL            Mobile         NaN          NaN        NaN
2              AL            Mobile      1984.0          8.0       16.0
3              CA            Orange         NaN          NaN        NaN
4              FL        Palm Beach         NaN          NaN        NaN
5       La Romana         La Romana         NaN          NaN        NaN
6              PA      Philadelphia      1905.0          5.0       17.0
7              PA           Latrobe      1957.0          1.0        6.0
8              VT             Essex      1962.0          6.0       11.0
9              NE        Falls City      1926.0          4.0       27.0
10             OH           Portage      1930.0          2.0       13.0
11             OH        Versailles      1935.0          6.0       11.0
12             AR       Little Rock         NaN          NaN        NaN
13             GA           Atlanta         NaN          NaN        NaN
14             MI             Flint         NaN          NaN        NaN
15             OH        Zanesville         NaN          NaN        NaN
16             MA       Newburyport         NaN          NaN        NaN
17             PA         New Eagle      1933.0          4.0       13.0
18             CA          Van Nuys         NaN          NaN        NaN
19             OH         Cleveland      1993.0          5.0       20.0
20             OK       Fort Towson      1939.0         11.0       11.0
21             GA          Columbus         NaN          NaN        NaN
22             CA          Torrance      2006.0          2.0       19.0
23             GA           Atlanta         NaN          NaN        NaN
24             NC             Bynum      2001.0         11.0       16.0
25             NC           Stanley      2004.0         12.0       16.0
26             NC       Forest City      1994.0         12.0        5.0
27             IL           Chicago      1973.0          6.0       23.0
28             TX           Terrell      1951.0          2.0        8.0
29             OH          Hamilton         NaN          NaN        NaN
...           ...               ...         ...          ...        ...
18816          WI        Auburndale         NaN          NaN        NaN
18817          PA        Pine Grove      1991.0         11.0       22.0
18818          NC        Washington         NaN          NaN        NaN
18819          CA        Carmichael         NaN          NaN        NaN
18820          MA        Pittsfield      1964.0          6.0       12.0
18821          PA      Phoenixville      1936.0          5.0       12.0
18822          WV          Holbrook      1949.0         10.0        6.0
18823          AR            Benton      1991.0          2.0       26.0
18824          NY           Astoria      1993.0          2.0       16.0
18825          TX           El Paso         NaN          NaN        NaN
18826          IL        Belleville         NaN          NaN        NaN
18827          NY          Brooklyn         NaN          NaN        NaN
18828          NV         Las Vegas         NaN          NaN        NaN
18829          NY  Long Island City      1985.0          5.0       29.0
18830          OH         Cleveland      1950.0          8.0       20.0
18831          IL            Eureka         NaN          NaN        NaN
18832          NY             Bronx         NaN          NaN        NaN
18833          NY          Brooklyn      1966.0          8.0       25.0
18834          CA          Whittier         NaN          NaN        NaN
18835          IA      Middle Amana      1982.0         11.0        2.0
18836          CA            Encino         NaN          NaN        NaN
18837      Panama            Panama         NaN          NaN        NaN
18838          CA       Chula Vista         NaN          NaN        NaN
18839          FL        Cape Coral         NaN          NaN        NaN
18840          PA        Pittsburgh         NaN          NaN        NaN
18841          CA     San Francisco      2005.0          3.0       25.0
18842          CA         San Mateo         NaN          NaN        NaN
18843          MI           Holland      2014.0          9.0        8.0
18844          MO         St. Louis      1978.0          3.0       27.0
18845          IL             Monee         NaN          NaN        NaN

         ...        name_last          name_given weight height bats throws  \
0        ...          Aardsma         David Allan  220.0   75.0    R      R
1        ...            Aaron         Henry Louis  180.0   72.0    R      R
2        ...            Aaron          Tommie Lee  190.0   75.0    R      R
3        ...             Aase      Donald William  190.0   75.0    R      R
4        ...             Abad       Fausto Andres  184.0   73.0    L      L
5        ...             Abad    Fernando Antonio  220.0   73.0    L      L
6        ...           Abadie             John W.  192.0   72.0    R      R
7        ...      Abbaticchio        Edward James  170.0   71.0    R      R
8        ...            Abbey           Bert Wood  175.0   71.0    R      R
9        ...            Abbey          Charles S.  169.0   68.0    L      L
10       ...           Abbott    Leander Franklin  190.0   71.0    R      R
11       ...           Abbott     Harry Frederick  180.0   70.0    R      R
12       ...           Abbott       William Glenn  200.0   78.0    R      R
13       ...           Abbott     Jeffrey William  190.0   74.0    R      L
14       ...           Abbott       James Anthony  200.0   75.0    L      L
15       ...           Abbott         Kurt Thomas  180.0   71.0    R      R
16       ...           Abbott       Lawrence Kyle  200.0   76.0    L      L
17       ...           Abbott           Ody Cleon  180.0   74.0    R      R
18       ...           Abbott          Paul David  185.0   75.0    R      R
19       ...             Aber       Albert Julius  195.0   74.0    L      L
20       ...      Abercrombie   Francis Patterson    NaN    NaN  NaN    NaN
21       ...      Abercrombie   Reginald Damascus  215.0   75.0    R      R
22       ...       Abernathie      William Edward  190.0   70.0    R      R
23       ...        Abernathy       Michael Brent  185.0   73.0    R      R
24       ...        Abernathy  Talmadge Lafayette  210.0   74.0    R      L
25       ...        Abernathy       Theodore Wade  215.0   76.0    R      R
26       ...        Abernathy      Virgil Woodrow  170.0   72.0    L      L
27       ...          Aberson  Clifford Alexander  200.0   72.0    R      R
28       ...            Ables       Harry Terrell  200.0   74.0    R      L
29       ...            Abner        Shawn Wesley  190.0   73.0    R      R
...      ...              ...                 ...    ...    ...  ...    ...
18816    ...       Zimmermann           Jordan M.  225.0   74.0    R      R
18817    ...        Zimmerman        Roy Franklin  187.0   74.0    L      L
18818    ...        Zimmerman        Ryan Wallace  220.0   75.0    R      R
18819    ...             Zink       Charles Tadao  190.0   73.0    R      R
18820    ...             Zink        Walter Noble  165.0   72.0    R      R
18821    ...             Zinn       Frank Patrick  150.0   68.0  NaN    NaN
18822    ...             Zinn                 Guy  170.0   70.0    L      R
18823    ...             Zinn        James Edward  195.0   72.0    L      R
18824    ...           Zinser     William Francis  185.0   73.0    R      R
18825    ...           Zinter        Alan Michael  200.0   74.0    B      R
18826    ...           Zipfel    Marion Sylvester  200.0   75.0    L      R
18827    ...             Zisk      Richard Walter  200.0   73.0    R      R
18828    ...             Zito       Barry William  205.0   74.0    L      L
18829    ...         Zitzmann      William Arthur  175.0   70.0    R      R
18830    ...            Zmich       Edward Albert  180.0   72.0    L      L
18831    ...          Zobrist     Benjamin Thomas  210.0   75.0    B      R
18832    ...       Zoccolillo          Peter Jude  200.0   74.0    L      R
18833    ...           Zoldak       Samuel Walter  185.0   71.0    L      L
18834    ...            Zosky        Edward James  175.0   72.0    R      R
18835    ...            Zuber       William Henry  195.0   74.0    R      R
18836    ...            Zuber          Jon Edward  190.0   73.0    L      L
18837    ...           Zuleta       Julio Ernesto  230.0   78.0    R      R
18838    ...           Zumaya         Joel Martin  215.0   75.0    R      R
18839    ...           Zunino     Michael Accorsi  220.0   74.0    R      R
18840    ...           Zupcic              Robert  220.0   76.0    R      R
18841    ...             Zupo        Frank Joseph  182.0   71.0    L      R
18842    ...          Zuvella                Paul  173.0   72.0    R      R
18843    ...         Zuverink              George  195.0   76.0    R      R
18844    ...         Zwilling     Edward Harrison  160.0   66.0    L      L
18845    ...             Zych       Anthony Aaron  190.0   75.0    R      R

            debut  final_game  retro_id   bbref_id
0      2004-04-06  2015-08-23  aardd001  aardsda01
1      1954-04-13  1976-10-03  aaroh101  aaronha01
2      1962-04-10  1971-09-26  aarot101  aaronto01
3      1977-07-26  1990-10-03  aased001   aasedo01
4      2001-09-10  2006-04-13  abada001   abadan01
5      2010-07-28  2015-10-03  abadf001   abadfe01
6      1875-04-26  1875-06-10  abadj101  abadijo01
7      1897-09-04  1910-09-15  abbae101  abbated01
8      1892-06-14  1896-09-23  abbeb101  abbeybe01
9      1893-08-16  1897-08-19  abbec101  abbeych01
10     1890-04-19  1890-05-23  abbod101  abbotda01
11     1903-04-25  1905-09-20  abbof101  abbotfr01
12     1973-07-29  1984-08-08  abbog001  abbotgl01
13     1997-06-10  2001-09-29  abboj002  abbotje01
14     1989-04-08  1999-07-21  abboj001  abbotji01
15     1993-09-07  2001-04-13  abbok002  abbotku01
16     1991-09-10  1996-08-24  abbok001  abbotky01
17     1910-09-10  1910-10-15  abboo101  abbotod01
18     1990-08-21  2004-08-07  abbop001  abbotpa01
19     1950-09-15  1957-09-11  abera101   aberal01
20     1871-10-21  1871-10-21  aberd101  abercda01
21     2006-04-04  2008-09-28  aberr001  abercre01
22     1952-09-27  1952-09-27  aberb101  abernbi01
23     2001-06-25  2005-09-29  aberb001  abernbr01
24     1942-09-19  1944-04-29  abert102  abernte01
25     1955-04-13  1972-09-30  abert101  abernte02
26     1946-07-28  1947-04-17  aberw101  abernwo01
27     1947-07-18  1949-05-09  aberc101  aberscl01
28     1905-09-04  1911-05-05  ableh101  ablesha01
29     1987-09-08  1992-10-03  abnes001  abnersh01
...           ...         ...       ...        ...
18816  2009-04-20  2015-09-30  zimmj003  zimmejo02
18817  1945-08-27  1945-09-30  zimmr101  zimmero01
18818  2005-09-01  2015-09-07  zimmr001  zimmery01
18819  2008-08-12  2008-08-12  zinkc001   zinkch01
18820  1921-07-06  1921-07-19  zinkw101   zinkwa01
18821  1888-04-18  1888-05-03  zinnf101   zinnfr01
18822  1911-09-11  1915-09-16  zinng101   zinngu01
18823  1919-09-04  1929-08-25  zinnj101   zinnji01
18824  1944-08-19  1944-08-26  zinsb101  zinsebi01
18825  2002-06-18  2004-10-03  zinta001  zinteal01
18826  1961-07-26  1962-09-30  zipfb101  zipfebu01
18827  1971-09-08  1983-09-21  ziskr101   ziskri01
18828  2000-07-22  2015-09-30  zitob001   zitoba01
18829  1919-04-27  1929-09-25  zitzb101  zitzmbi01
18830  1910-07-23  1911-06-01  zmice101  zmiched01
18831  2006-08-01  2015-10-04  zobrb001  zobribe01
18832  2003-09-05  2003-09-28  zoccp001  zoccope01
18833  1944-05-13  1952-08-26  zolds101  zoldasa01
18834  1991-09-02  2000-10-01  zoske001  zoskyed01
18835  1936-09-16  1947-09-23  zubeb101  zuberbi01
18836  1996-04-19  1998-09-27  zubej001  zuberjo01
18837  2000-04-06  2001-06-25  zulej001  zuletju01
18838  2006-04-03  2010-06-28  zumaj001  zumayjo01
18839  2013-06-12  2015-08-27  zunim001  zuninmi01
18840  1991-09-07  1994-08-04  zupcb001  zupcibo01
18841  1957-07-01  1961-05-09  zupof101   zupofr01
18842  1982-09-04  1991-05-02  zuvep001  zuvelpa01
18843  1951-04-21  1959-06-15  zuveg101  zuverge01
18844  1910-08-14  1916-07-12  zwild101  zwilldu01
18845  2015-09-04  2015-10-03  zycht001   zychto01

[18846 rows x 24 columns]

In [4]:
df.columns.values

array(['player_id', 'birth_year', 'birth_month', 'birth_day',
       'birth_country', 'birth_state', 'birth_city', 'death_year',
       'death_month', 'death_day', 'death_country', 'death_state',
       'death_city', 'name_first', 'name_last', 'name_given', 'weight',
       'height', 'bats', 'throws', 'debut', 'final_game', 'retro_id',
       'bbref_id'], dtype=object)

In [5]:
df = df.drop(columns=[ 'death_year','death_month', 'death_day', 'death_country', 'death_state','death_city','name_given','retro_id','bbref_id'])

In [6]:
df

,player_id,birth_year,birth_month,birth_day,birth_country,birth_state,birth_city,name_first,name_last,weight,height,bats,throws,debut,final_game
0,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,David,Aardsma,220.0,75.0,R,R,2004-04-06,2015-08-23
1,aaronha01,1934.0,2.0,5.0,USA,AL,Mobile,Hank,Aaron,180.0,72.0,R,R,1954-04-13,1976-10-03
2,aaronto01,1939.0,8.0,5.0,USA,AL,Mobile,Tommie,Aaron,190.0,75.0,R,R,1962-04-10,1971-09-26
3,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,Don,Aase,190.0,75.0,R,R,1977-07-26,1990-10-03
4,abadan01,1972.0,8.0,25.0,USA,FL,Palm Beach,Andy,Abad,184.0,73.0,L,L,2001-09-10,2006-04-13
5,abadfe01,1985.0,12.0,17.0,D.R.,La Romana,La Romana,Fernando,Abad,220.0,73.0,L,L,2010-07-28,2015-10-03
6,abadijo01,1854.0,11.0,4.0,USA,PA,Philadelphia,John,Abadie,192.0,72.0,R,R,1875-04-26,1875-06-10
7,abbated01,1877.0,4.0,15.0,USA,PA,Latrobe,Ed,Abbaticchio,170.0,71.0,R,R,1897-09-04,1910-09-15
8,abbeybe01,1869.0,11.0,11.0,USA,VT,Essex,Bert,Abbey,175.0,71.0,R,R,1892-06-14,1896-09-23
9,abbeych01,1866.0,10.0,14.0,USA,NE,Falls City,Charlie,Abbey,169.0,68.0,L,L,1893-08-16,1897-08-19
10,abbotda01,1862.0,3.0,16.0,USA,OH,Portage,Dan,Abbott,190.0,71.0,R,R,1890-04-19,1890-05-23
11,abbotfr01,1874.0,10.0,22.0,USA,OH,Versailles,Fred,Abbott,180.0,70.0,R,R,1903-04-25,1905-09-20
12,abbotgl01,1951.0,2.0,16.0,USA,AR,Little Rock,Glenn,Abbott,200.0,78.0,R,R,1973-07-29,1984-08-08
13,abbotje01,1972.0,8.0,17.0,USA,GA,Atlanta,Jeff,Abbott,190.0,74.0,R,L,1997-06-10,2001-09-29
14,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,Jim,Abbott,200.0,75.0,L,L,1989-04-08,1999-07-21
15,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,Kurt,Abbott,180.0,71.0,R,R,1993-09-07,2001-04-13
16,abbotky01,1968.0,2.0,18.0,USA,MA,Newburyport,Kyle,Abbott,200.0,76.0,L,L,1991-09-10,1996-08-24
17,abbotod01,1888.0,9.0,5.0,USA,PA,New Eagle,Ody,Abbott,180.0,74.0,R,R,1910-09-10,1910-10-15
18,abbotpa01,1967.0,9.0,15.0,USA,CA,Van Nuys,Paul,Abbott,185.0,75.0,R,R,1990-08-21,2004-08-07
19,aberal01,1927.0,7.0,31.0,USA,OH,Cleveland,Al,Aber,195.0,74.0,L,L,1950-09-15,1957-09-11
20,abercda01,1850.0,1.0,2.0,USA,OK,Fort Towson,Frank,Abercrombie,NaN,NaN,NaN,NaN,1871-10-21,1871-10-21
21,abercre01,1980.0,7.0,15.0,USA,GA,Columbus,Reggie,Abercrombie,215.0,75.0,R,R,2006-04-04,2008-09-28
22,abernbi01,1929.0,1.0,30.0,USA,CA,Torrance,Bill,Abernathie,190.0,70.0,R,R,1952-09-27,1952-09-27
23,abernbr01,1977.0,9.0,23.0,USA,GA,Atlanta,Brent,Abernathy,185.0,73.0,R,R,2001-06-25,2005-09-29
24,abernte01,1921.0,10.0,30.0,USA,NC,Bynum,Ted,Abernathy,210.0,74.0,R,L,1942-09-19,1944-04-29
25,abernte02,1933.0,3.0,6.0,USA,NC,Stanley,Ted,Abernathy,215.0,76.0,R,R,1955-04-13,1972-09-30
26,abernwo01,1915.0,2.0,1.0,USA,NC,Forest City,Woody,Abernathy,170.0,72.0,L,L,1946-07-28,1947-04-17
27,aberscl01,1921.0,8.0,28.0,USA,IL,Chicago,Cliff,Aberson,200.0,72.0,R,R,1947-07-18,1949-05-09
28,ablesha01,1883.0,10.0,4.0,USA,TX,Terrell,Harry,Ables,200.0,74.0,R,L,1905-09-04,1911-05-05
29,abnersh01,1966.0,6.0,17.0,USA,OH,Hamilton,Shawn,Abner,190.0,73.0,R,R,1987-09-08,1992-10-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18816,zimmejo02,1986.0,5.0,23.0,USA,WI,Auburndale,Jordan,Zimmermann,225.0,74.0,R,R,2009-04-20,2015-09-30
18817,zimmero01,1916.0,9.0,13.0,USA,PA,Pine Grove,Roy,Zimmerman,187.0,74.0,L,L,1945-08-27,1945-09-30
18818,zimmery01,1984.0,9.0,28.0,USA,NC,Washington,Ryan,Zimmerman,220.0,75.0,R,R,2005-09-01,2015-09-07
18819,zinkch01,1979.0,8.0,26.0,USA,CA,Carmichael,Charlie,Zink,190.0,73.0,R,R,2008-08-12,2008-08-12
18820,zinkwa01,1898.0,11.0,21.0,USA,MA,Pittsfield,Walter,Zink,165.0,72.0,R,R,1921-07-06,1921-07-19
18821,zinnfr01,1865.0,12.0,21.0,USA,PA,Phoenixville,Frank,Zinn,150.0,68.0,NaN,NaN,1888-04-18,1888-05-03
18822,zinngu01,1887.0,2.0,13.0,USA,WV,Holbrook,Guy,Zinn,170.0,70.0,L,R,1911-09-11,1915-09-16
18823,zinnji01,1895.0,1.0,21.0,USA,AR,Benton,Jimmy,Zinn,195.0,72.0,L,R,1919-09-04,1929-08-25
18824,zinsebi01,1918.0,1.0,6.0,USA,NY,Astoria,Bill,Zinser,185.0,73.0,R,R,1944-08-19,1944-08-26
18825,zinteal01,1968.0,5.0,19.0,USA,TX,El Paso,Alan,Zinter,200.0,74.0,B,R,2002-06-18,2004-10-03
18826,zipfebu01,1938.0,11.0,18.0,USA,IL,Belleville,Bud,Zipfel,200.0,75.0,L,R,1961-07-26,1962-09-30
18827,ziskri01,1949.0,2.0,6.0,USA,NY,Brooklyn,Richie,Zisk,200.0,73.0,R,R,1971-09-08,1983-09-21
18828,zitoba01,1978.0,5.0,13.0,USA,NV,Las Vegas,Barry,Zito,205.0,74.0,L,L,2000-07-22,2015-09-30
18829,zitzmbi01,1895.0,11.0,19.0,USA,NY,Long Island City,Billy,Zitzmann,175.0,70.0,R,R,1919-04-27,1929-09-25
18830,zmiched01,1884.0,10.0,1.0,USA,OH,Cleveland,Ed,Zmich,180.0,72.0,L,L,1910-07-23,1911-06-01
18831,zobribe01,1981.0,5.0,26.0,USA,IL,Eureka,Ben,Zobrist,210.0,75.0,B,R,2006-08-01,2015-10-04
18832,zoccope01,1977.0,2.0,6.0,USA,NY,Bronx,Peter,Zoccolillo,200.0,74.0,L,R,2003-09-05,2003-09-28
18833,zoldasa01,1918.0,12.0,8.0,USA,NY,Brooklyn,Sam,Zoldak,185.0,71.0,L,L,1944-05-13,1952-08-26
18834,zoskyed01,1968.0,2.0,10.0,USA,CA,Whittier,Eddie,Zosky,175.0,72.0,R,R,1991-09-02,2000-10-01
18835,zuberbi01,1913.0,3.0,26.0,USA,IA,Middle Amana,Bill,Zuber,195.0,74.0,R,R,1936-09-16,1947-09-23
18836,zuberjo01,1969.0,12.0,10.0,USA,CA,Encino,Jon,Zuber,190.0,73.0,L,L,1996-04-19,1998-09-27
18837,zuletju01,1975.0,3.0,28.0,Panama,Panama,Panama,Julio,Zuleta,230.0,78.0,R,R,2000-04-06,2001-06-25
18838,zumayjo01,1984.0,11.0,9.0,USA,CA,Chula Vista,Joel,Zumaya,215.0,75.0,R,R,2006-04-03,2010-06-28
18839,zuninmi01,1991.0,3.0,25.0,USA,FL,Cape Coral,Mike,Zunino,220.0,74.0,R,R,2013-06-12,2015-08-27
18840,zupcibo01,1966.0,8.0,18.0,USA,PA,Pittsburgh,Bob,Zupcic,220.0,76.0,R,R,1991-09-07,1994-08-04
18841,zupofr01,1939.0,8.0,29.0,USA,CA,San Francisco,Frank,Zupo,182.0,71.0,L,R,1957-07-01,1961-05-09
18842,zuvelpa01,1958.0,10.0,31.0,USA,CA,San Mateo,Paul,Zuvella,173.0,72.0,R,R,1982-09-04,1991-05-02
18843,zuverge01,1924.0,8.0,20.0,USA,MI,Holland,George,Zuverink,195.0,76.0,R,R,1951-04-21,1959-06-15
18844,zwilldu01,1888.0,11.0,2.0,USA,MO,St. Louis,Dutch,Zwilling,160.0,66.0,L,L,1910-08-14,1916-07-12
18845,zychto01,1990.0,8.0,7.0,USA,IL,Monee,Tony,Zych,190.0,75.0,R,R,2015-09-04,2015-10-03

In [7]:
debut_year= df['debut'].str[:4]
debut_year

0        2004
1        1954
2        1962
3        1977
4        2001
5        2010
6        1875
7        1897
8        1892
9        1893
10       1890
11       1903
12       1973
13       1997
14       1989
15       1993
16       1991
17       1910
18       1990
19       1950
20       1871
21       2006
22       1952
23       2001
24       1942
25       1955
26       1946
27       1947
28       1905
29       1987
         ...
18816    2009
18817    1945
18818    2005
18819    2008
18820    1921
18821    1888
18822    1911
18823    1919
18824    1944
18825    2002
18826    1961
18827    1971
18828    2000
18829    1919
18830    1910
18831    2006
18832    2003
18833    1944
18834    1991
18835    1936
18836    1996
18837    2000
18838    2006
18839    2013
18840    1991
18841    1957
18842    1982
18843    1951
18844    1910
18845    2015
Name: debut, Length: 18846, dtype: object

In [8]:
df['debut_year']= debut_year

In [9]:
df

,player_id,birth_year,birth_month,birth_day,birth_country,birth_state,birth_city,name_first,name_last,weight,height,bats,throws,debut,final_game,debut_year
0,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,David,Aardsma,220.0,75.0,R,R,2004-04-06,2015-08-23,2004
1,aaronha01,1934.0,2.0,5.0,USA,AL,Mobile,Hank,Aaron,180.0,72.0,R,R,1954-04-13,1976-10-03,1954
2,aaronto01,1939.0,8.0,5.0,USA,AL,Mobile,Tommie,Aaron,190.0,75.0,R,R,1962-04-10,1971-09-26,1962
3,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,Don,Aase,190.0,75.0,R,R,1977-07-26,1990-10-03,1977
4,abadan01,1972.0,8.0,25.0,USA,FL,Palm Beach,Andy,Abad,184.0,73.0,L,L,2001-09-10,2006-04-13,2001
5,abadfe01,1985.0,12.0,17.0,D.R.,La Romana,La Romana,Fernando,Abad,220.0,73.0,L,L,2010-07-28,2015-10-03,2010
6,abadijo01,1854.0,11.0,4.0,USA,PA,Philadelphia,John,Abadie,192.0,72.0,R,R,1875-04-26,1875-06-10,1875
7,abbated01,1877.0,4.0,15.0,USA,PA,Latrobe,Ed,Abbaticchio,170.0,71.0,R,R,1897-09-04,1910-09-15,1897
8,abbeybe01,1869.0,11.0,11.0,USA,VT,Essex,Bert,Abbey,175.0,71.0,R,R,1892-06-14,1896-09-23,1892
9,abbeych01,1866.0,10.0,14.0,USA,NE,Falls City,Charlie,Abbey,169.0,68.0,L,L,1893-08-16,1897-08-19,1893
10,abbotda01,1862.0,3.0,16.0,USA,OH,Portage,Dan,Abbott,190.0,71.0,R,R,1890-04-19,1890-05-23,1890
11,abbotfr01,1874.0,10.0,22.0,USA,OH,Versailles,Fred,Abbott,180.0,70.0,R,R,1903-04-25,1905-09-20,1903
12,abbotgl01,1951.0,2.0,16.0,USA,AR,Little Rock,Glenn,Abbott,200.0,78.0,R,R,1973-07-29,1984-08-08,1973
13,abbotje01,1972.0,8.0,17.0,USA,GA,Atlanta,Jeff,Abbott,190.0,74.0,R,L,1997-06-10,2001-09-29,1997
14,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,Jim,Abbott,200.0,75.0,L,L,1989-04-08,1999-07-21,1989
15,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,Kurt,Abbott,180.0,71.0,R,R,1993-09-07,2001-04-13,1993
16,abbotky01,1968.0,2.0,18.0,USA,MA,Newburyport,Kyle,Abbott,200.0,76.0,L,L,1991-09-10,1996-08-24,1991
17,abbotod01,1888.0,9.0,5.0,USA,PA,New Eagle,Ody,Abbott,180.0,74.0,R,R,1910-09-10,1910-10-15,1910
18,abbotpa01,1967.0,9.0,15.0,USA,CA,Van Nuys,Paul,Abbott,185.0,75.0,R,R,1990-08-21,2004-08-07,1990
19,aberal01,1927.0,7.0,31.0,USA,OH,Cleveland,Al,Aber,195.0,74.0,L,L,1950-09-15,1957-09-11,1950
20,abercda01,1850.0,1.0,2.0,USA,OK,Fort Towson,Frank,Abercrombie,NaN,NaN,NaN,NaN,1871-10-21,1871-10-21,1871
21,abercre01,1980.0,7.0,15.0,USA,GA,Columbus,Reggie,Abercrombie,215.0,75.0,R,R,2006-04-04,2008-09-28,2006
22,abernbi01,1929.0,1.0,30.0,USA,CA,Torrance,Bill,Abernathie,190.0,70.0,R,R,1952-09-27,1952-09-27,1952
23,abernbr01,1977.0,9.0,23.0,USA,GA,Atlanta,Brent,Abernathy,185.0,73.0,R,R,2001-06-25,2005-09-29,2001
24,abernte01,1921.0,10.0,30.0,USA,NC,Bynum,Ted,Abernathy,210.0,74.0,R,L,1942-09-19,1944-04-29,1942
25,abernte02,1933.0,3.0,6.0,USA,NC,Stanley,Ted,Abernathy,215.0,76.0,R,R,1955-04-13,1972-09-30,1955
26,abernwo01,1915.0,2.0,1.0,USA,NC,Forest City,Woody,Abernathy,170.0,72.0,L,L,1946-07-28,1947-04-17,1946
27,aberscl01,1921.0,8.0,28.0,USA,IL,Chicago,Cliff,Aberson,200.0,72.0,R,R,1947-07-18,1949-05-09,1947
28,ablesha01,1883.0,10.0,4.0,USA,TX,Terrell,Harry,Ables,200.0,74.0,R,L,1905-09-04,1911-05-05,1905
29,abnersh01,1966.0,6.0,17.0,USA,OH,Hamilton,Shawn,Abner,190.0,73.0,R,R,1987-09-08,1992-10-03,1987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18816,zimmejo02,1986.0,5.0,23.0,USA,WI,Auburndale,Jordan,Zimmermann,225.0,74.0,R,R,2009-04-20,2015-09-30,2009
18817,zimmero01,1916.0,9.0,13.0,USA,PA,Pine Grove,Roy,Zimmerman,187.0,74.0,L,L,1945-08-27,1945-09-30,1945
18818,zimmery01,1984.0,9.0,28.0,USA,NC,Washington,Ryan,Zimmerman,220.0,75.0,R,R,2005-09-01,2015-09-07,2005
18819,zinkch01,1979.0,8.0,26.0,USA,CA,Carmichael,Charlie,Zink,190.0,73.0,R,R,2008-08-12,2008-08-12,2008
18820,zinkwa01,1898.0,11.0,21.0,USA,MA,Pittsfield,Walter,Zink,165.0,72.0,R,R,1921-07-06,1921-07-19,1921
18821,zinnfr01,1865.0,12.0,21.0,USA,PA,Phoenixville,Frank,Zinn,150.0,68.0,NaN,NaN,1888-04-18,1888-05-03,1888
18822,zinngu01,1887.0,2.0,13.0,USA,WV,Holbrook,Guy,Zinn,170.0,70.0,L,R,1911-09-11,1915-09-16,1911
18823,zinnji01,1895.0,1.0,21.0,USA,AR,Benton,Jimmy,Zinn,195.0,72.0,L,R,1919-09-04,1929-08-25,1919
18824,zinsebi01,1918.0,1.0,6.0,USA,NY,Astoria,Bill,Zinser,185.0,73.0,R,R,1944-08-19,1944-08-26,1944
18825,zinteal01,1968.0,5.0,19.0,USA,TX,El Paso,Alan,Zinter,200.0,74.0,B,R,2002-06-18,2004-10-03,2002
18826,zipfebu01,1938.0,11.0,18.0,USA,IL,Belleville,Bud,Zipfel,200.0,75.0,L,R,1961-07-26,1962-09-30,1961
18827,ziskri01,1949.0,2.0,6.0,USA,NY,Brooklyn,Richie,Zisk,200.0,73.0,R,R,1971-09-08,1983-09-21,1971
18828,zitoba01,1978.0,5.0,13.0,USA,NV,Las Vegas,Barry,Zito,205.0,74.0,L,L,2000-07-22,2015-09-30,2000
18829,zitzmbi01,1895.0,11.0,19.0,USA,NY,Long Island City,Billy,Zitzmann,175.0,70.0,R,R,1919-04-27,1929-09-25,1919
18830,zmiched01,1884.0,10.0,1.0,USA,OH,Cleveland,Ed,Zmich,180.0,72.0,L,L,1910-07-23,1911-06-01,1910
18831,zobribe01,1981.0,5.0,26.0,USA,IL,Eureka,Ben,Zobrist,210.0,75.0,B,R,2006-08-01,2015-10-04,2006
18832,zoccope01,1977.0,2.0,6.0,USA,NY,Bronx,Peter,Zoccolillo,200.0,74.0,L,R,2003-09-05,2003-09-28,2003
18833,zoldasa01,1918.0,12.0,8.0,USA,NY,Brooklyn,Sam,Zoldak,185.0,71.0,L,L,1944-05-13,1952-08-26,1944
18834,zoskyed01,1968.0,2.0,10.0,USA,CA,Whittier,Eddie,Zosky,175.0,72.0,R,R,1991-09-02,2000-10-01,1991
18835,zuberbi01,1913.0,3.0,26.0,USA,IA,Middle Amana,Bill,Zuber,195.0,74.0,R,R,1936-09-16,1947-09-23,1936
18836,zuberjo01,1969.0,12.0,10.0,USA,CA,Encino,Jon,Zuber,190.0,73.0,L,L,1996-04-19,1998-09-27,1996
18837,zuletju01,1975.0,3.0,28.0,Panama,Panama,Panama,Julio,Zuleta,230.0,78.0,R,R,2000-04-06,2001-06-25,2000
18838,zumayjo01,1984.0,11.0,9.0,USA,CA,Chula Vista,Joel,Zumaya,215.0,75.0,R,R,2006-04-03,2010-06-28,2006
18839,zuninmi01,1991.0,3.0,25.0,USA,FL,Cape Coral,Mike,Zunino,220.0,74.0,R,R,2013-06-12,2015-08-27,2013
18840,zupcibo01,1966.0,8.0,18.0,USA,PA,Pittsburgh,Bob,Zupcic,220.0,76.0,R,R,1991-09-07,1994-08-04,1991
18841,zupofr01,1939.0,8.0,29.0,USA,CA,San Francisco,Frank,Zupo,182.0,71.0,L,R,1957-07-01,1961-05-09,1957
18842,zuvelpa01,1958.0,10.0,31.0,USA,CA,San Mateo,Paul,Zuvella,173.0,72.0,R,R,1982-09-04,1991-05-02,1982
18843,zuverge01,1924.0,8.0,20.0,USA,MI,Holland,George,Zuverink,195.0,76.0,R,R,1951-04-21,1959-06-15,1951
18844,zwilldu01,1888.0,11.0,2.0,USA,MO,St. Louis,Dutch,Zwilling,160.0,66.0,L,L,1910-08-14,1916-07-12,1910
18845,zychto01,1990.0,8.0,7.0,USA,IL,Monee,Tony,Zych,190.0,75.0,R,R,2015-09-04,2015-10-03,2015

In [10]:
# Drop all rows with missing information
df = df.dropna(how='any')

In [11]:
df

,player_id,birth_year,birth_month,birth_day,birth_country,birth_state,birth_city,name_first,name_last,weight,height,bats,throws,debut,final_game,debut_year
0,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,David,Aardsma,220.0,75.0,R,R,2004-04-06,2015-08-23,2004
1,aaronha01,1934.0,2.0,5.0,USA,AL,Mobile,Hank,Aaron,180.0,72.0,R,R,1954-04-13,1976-10-03,1954
2,aaronto01,1939.0,8.0,5.0,USA,AL,Mobile,Tommie,Aaron,190.0,75.0,R,R,1962-04-10,1971-09-26,1962
3,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,Don,Aase,190.0,75.0,R,R,1977-07-26,1990-10-03,1977
4,abadan01,1972.0,8.0,25.0,USA,FL,Palm Beach,Andy,Abad,184.0,73.0,L,L,2001-09-10,2006-04-13,2001
5,abadfe01,1985.0,12.0,17.0,D.R.,La Romana,La Romana,Fernando,Abad,220.0,73.0,L,L,2010-07-28,2015-10-03,2010
6,abadijo01,1854.0,11.0,4.0,USA,PA,Philadelphia,John,Abadie,192.0,72.0,R,R,1875-04-26,1875-06-10,1875
7,abbated01,1877.0,4.0,15.0,USA,PA,Latrobe,Ed,Abbaticchio,170.0,71.0,R,R,1897-09-04,1910-09-15,1897
8,abbeybe01,1869.0,11.0,11.0,USA,VT,Essex,Bert,Abbey,175.0,71.0,R,R,1892-06-14,1896-09-23,1892
9,abbeych01,1866.0,10.0,14.0,USA,NE,Falls City,Charlie,Abbey,169.0,68.0,L,L,1893-08-16,1897-08-19,1893
10,abbotda01,1862.0,3.0,16.0,USA,OH,Portage,Dan,Abbott,190.0,71.0,R,R,1890-04-19,1890-05-23,1890
11,abbotfr01,1874.0,10.0,22.0,USA,OH,Versailles,Fred,Abbott,180.0,70.0,R,R,1903-04-25,1905-09-20,1903
12,abbotgl01,1951.0,2.0,16.0,USA,AR,Little Rock,Glenn,Abbott,200.0,78.0,R,R,1973-07-29,1984-08-08,1973
13,abbotje01,1972.0,8.0,17.0,USA,GA,Atlanta,Jeff,Abbott,190.0,74.0,R,L,1997-06-10,2001-09-29,1997
14,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,Jim,Abbott,200.0,75.0,L,L,1989-04-08,1999-07-21,1989
15,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,Kurt,Abbott,180.0,71.0,R,R,1993-09-07,2001-04-13,1993
16,abbotky01,1968.0,2.0,18.0,USA,MA,Newburyport,Kyle,Abbott,200.0,76.0,L,L,1991-09-10,1996-08-24,1991
17,abbotod01,1888.0,9.0,5.0,USA,PA,New Eagle,Ody,Abbott,180.0,74.0,R,R,1910-09-10,1910-10-15,1910
18,abbotpa01,1967.0,9.0,15.0,USA,CA,Van Nuys,Paul,Abbott,185.0,75.0,R,R,1990-08-21,2004-08-07,1990
19,aberal01,1927.0,7.0,31.0,USA,OH,Cleveland,Al,Aber,195.0,74.0,L,L,1950-09-15,1957-09-11,1950
21,abercre01,1980.0,7.0,15.0,USA,GA,Columbus,Reggie,Abercrombie,215.0,75.0,R,R,2006-04-04,2008-09-28,2006
22,abernbi01,1929.0,1.0,30.0,USA,CA,Torrance,Bill,Abernathie,190.0,70.0,R,R,1952-09-27,1952-09-27,1952
23,abernbr01,1977.0,9.0,23.0,USA,GA,Atlanta,Brent,Abernathy,185.0,73.0,R,R,2001-06-25,2005-09-29,2001
24,abernte01,1921.0,10.0,30.0,USA,NC,Bynum,Ted,Abernathy,210.0,74.0,R,L,1942-09-19,1944-04-29,1942
25,abernte02,1933.0,3.0,6.0,USA,NC,Stanley,Ted,Abernathy,215.0,76.0,R,R,1955-04-13,1972-09-30,1955
26,abernwo01,1915.0,2.0,1.0,USA,NC,Forest City,Woody,Abernathy,170.0,72.0,L,L,1946-07-28,1947-04-17,1946
27,aberscl01,1921.0,8.0,28.0,USA,IL,Chicago,Cliff,Aberson,200.0,72.0,R,R,1947-07-18,1949-05-09,1947
28,ablesha01,1883.0,10.0,4.0,USA,TX,Terrell,Harry,Ables,200.0,74.0,R,L,1905-09-04,1911-05-05,1905
29,abnersh01,1966.0,6.0,17.0,USA,OH,Hamilton,Shawn,Abner,190.0,73.0,R,R,1987-09-08,1992-10-03,1987
30,abramca01,1924.0,3.0,2.0,USA,PA,Philadelphia,Cal,Abrams,185.0,72.0,L,L,1949-04-19,1956-05-09,1949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18815,zimmejo01,1975.0,4.0,28.0,CAN,BC,Kelowna,Jordan,Zimmerman,200.0,72.0,R,L,1999-05-17,1999-07-02,1999
18816,zimmejo02,1986.0,5.0,23.0,USA,WI,Auburndale,Jordan,Zimmermann,225.0,74.0,R,R,2009-04-20,2015-09-30,2009
18817,zimmero01,1916.0,9.0,13.0,USA,PA,Pine Grove,Roy,Zimmerman,187.0,74.0,L,L,1945-08-27,1945-09-30,1945
18818,zimmery01,1984.0,9.0,28.0,USA,NC,Washington,Ryan,Zimmerman,220.0,75.0,R,R,2005-09-01,2015-09-07,2005
18819,zinkch01,1979.0,8.0,26.0,USA,CA,Carmichael,Charlie,Zink,190.0,73.0,R,R,2008-08-12,2008-08-12,2008
18820,zinkwa01,1898.0,11.0,21.0,USA,MA,Pittsfield,Walter,Zink,165.0,72.0,R,R,1921-07-06,1921-07-19,1921
18822,zinngu01,1887.0,2.0,13.0,USA,WV,Holbrook,Guy,Zinn,170.0,70.0,L,R,1911-09-11,1915-09-16,1911
18823,zinnji01,1895.0,1.0,21.0,USA,AR,Benton,Jimmy,Zinn,195.0,72.0,L,R,1919-09-04,1929-08-25,1919
18824,zinsebi01,1918.0,1.0,6.0,USA,NY,Astoria,Bill,Zinser,185.0,73.0,R,R,1944-08-19,1944-08-26,1944
18825,zinteal01,1968.0,5.0,19.0,USA,TX,El Paso,Alan,Zinter,200.0,74.0,B,R,2002-06-18,2004-10-03,2002
18826,zipfebu01,1938.0,11.0,18.0,USA,IL,Belleville,Bud,Zipfel,200.0,75.0,L,R,1961-07-26,1962-09-30,1961
18827,ziskri01,1949.0,2.0,6.0,USA,NY,Brooklyn,Richie,Zisk,200.0,73.0,R,R,1971-09-08,1983-09-21,1971
18828,zitoba01,1978.0,5.0,13.0,USA,NV,Las Vegas,Barry,Zito,205.0,74.0,L,L,2000-07-22,2015-09-30,2000
18829,zitzmbi01,1895.0,11.0,19.0,USA,NY,Long Island City,Billy,Zitzmann,175.0,70.0,R,R,1919-04-27,1929-09-25,1919
18830,zmiched01,1884.0,10.0,1.0,USA,OH,Cleveland,Ed,Zmich,180.0,72.0,L,L,1910-07-23,1911-06-01,1910
18831,zobribe01,1981.0,5.0,26.0,USA,IL,Eureka,Ben,Zobrist,210.0,75.0,B,R,2006-08-01,2015-10-04,2006
18832,zoccope01,1977.0,2.0,6.0,USA,NY,Bronx,Peter,Zoccolillo,200.0,74.0,L,R,2003-09-05,2003-09-28,2003
18833,zoldasa01,1918.0,12.0,8.0,USA,NY,Brooklyn,Sam,Zoldak,185.0,71.0,L,L,1944-05-13,1952-08-26,1944
18834,zoskyed01,1968.0,2.0,10.0,USA,CA,Whittier,Eddie,Zosky,175.0,72.0,R,R,1991-09-02,2000-10-01,1991
18835,zuberbi01,1913.0,3.0,26.0,USA,IA,Middle Amana,Bill,Zuber,195.0,74.0,R,R,1936-09-16,1947-09-23,1936
18836,zuberjo01,1969.0,12.0,10.0,USA,CA,Encino,Jon,Zuber,190.0,73.0,L,L,1996-04-19,1998-09-27,1996
18837,zuletju01,1975.0,3.0,28.0,Panama,Panama,Panama,Julio,Zuleta,230.0,78.0,R,R,2000-04-06,2001-06-25,2000
18838,zumayjo01,1984.0,11.0,9.0,USA,CA,Chula Vista,Joel,Zumaya,215.0,75.0,R,R,2006-04-03,2010-06-28,2006
18839,zuninmi01,1991.0,3.0,25.0,USA,FL,Cape Coral,Mike,Zunino,220.0,74.0,R,R,2013-06-12,2015-08-27,2013
18840,zupcibo01,1966.0,8.0,18.0,USA,PA,Pittsburgh,Bob,Zupcic,220.0,76.0,R,R,1991-09-07,1994-08-04,1991
18841,zupofr01,1939.0,8.0,29.0,USA,CA,San Francisco,Frank,Zupo,182.0,71.0,L,R,1957-07-01,1961-05-09,1957
18842,zuvelpa01,1958.0,10.0,31.0,USA,CA,San Mateo,Paul,Zuvella,173.0,72.0,R,R,1982-09-04,1991-05-02,1982
18843,zuverge01,1924.0,8.0,20.0,USA,MI,Holland,George,Zuverink,195.0,76.0,R,R,1951-04-21,1959-06-15,1951
18844,zwilldu01,1888.0,11.0,2.0,USA,MO,St. Louis,Dutch,Zwilling,160.0,66.0,L,L,1910-08-14,1916-07-12,1910
18845,zychto01,1990.0,8.0,7.0,USA,IL,Monee,Tony,Zych,190.0,75.0,R,R,2015-09-04,2015-10-03,2015

In [12]:
df.dtypes

player_id         object
birth_year       float64
birth_month      float64
birth_day        float64
birth_country     object
birth_state       object
birth_city        object
name_first        object
name_last         object
weight           float64
height           float64
bats              object
throws            object
debut             object
final_game        object
debut_year        object
dtype: object

In [19]:
df.birth_year = df.birth_year.astype(int)
df.birth_month = df.birth_month.astype(int)
df.birth_day = df.birth_day.astype(int)
df.debut_year = df.debut_year.astype(int)

C:\Users\basis\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [20]:
df.dtypes

player_id         object
birth_year         int32
birth_month        int32
birth_day          int32
birth_country     object
birth_state       object
birth_city        object
name_first        object
name_last         object
weight           float64
height           float64
bats              object
throws            object
debut             object
final_game        object
debut_year         int32
dtype: object

In [27]:
filter_df = df.loc[(df['debut_year'] > 1989)] 
player_df = filter_df.sort_values(by=['debut_year'])
player_df

,player_id,birth_year,birth_month,birth_day,birth_country,birth_state,birth_city,name_first,name_last,weight,height,bats,throws,debut,final_game,debut_year
9803,lewisda01,1967,8,28,USA,CA,Berkeley,Darren,Lewis,180.0,72.0,R,R,1990-08-21,2002-07-30,1990
13505,plantph01,1969,1,27,USA,NH,Manchester,Phil,Plantier,175.0,72.0,L,R,1990-08-21,1997-09-28,1990
3176,coleal01,1965,8,17,USA,NC,Fayetteville,Alex,Cole,170.0,74.0,L,L,1990-07-27,1996-05-22,1990
5704,frymatr01,1969,3,25,USA,KY,Lexington,Travis,Fryman,180.0,73.0,R,R,1990-07-07,2002-09-29,1990
11253,mcraebr01,1967,8,27,USA,FL,Bradenton,Brian,McRae,175.0,72.0,B,R,1990-08-07,1999-10-03,1990
5852,garceri01,1971,5,18,Venezuela,Aragua,Maracay,Rich,Garces,250.0,72.0,R,R,1990-09-18,2002-07-20,1990
15542,sherrti01,1965,9,10,USA,AR,Harrison,Tim,Sherrill,170.0,71.0,L,L,1990-08-14,1991-06-16,1990
5897,gardimi01,1965,10,19,CAN,ON,Sarnia,Mike,Gardiner,185.0,72.0,B,R,1990-09-08,1995-07-02,1990
7930,howarth01,1964,12,11,USA,OH,Middletown,Thomas,Howard,200.0,74.0,B,R,1990-07-03,2000-10-01,1990
7929,howarst01,1963,12,7,USA,CA,Oakland,Steve,Howard,205.0,74.0,R,R,1990-06-16,1990-07-17,1990
13156,penage01,1967,3,29,D.R.,Distrito Nacional,Los Alcarrizos,Geronimo,Pena,170.0,73.0,B,R,1990-09-05,1996-09-29,1990
17624,wagnehe02,1968,11,26,D.R.,San Juan,San Juan de la Maguana,Hector,Wagner,185.0,75.0,R,R,1990-09-10,1991-06-24,1990
1091,bellmi01,1968,4,22,USA,NY,Lewiston,Mike,Bell,175.0,73.0,L,L,1990-05-02,1991-10-06,1990
6135,gilkebe01,1966,9,24,USA,MO,St. Louis,Bernard,Gilkey,170.0,72.0,R,R,1990-09-04,2001-10-07,1990
2679,casiala01,1965,10,28,USA,CA,Lynwood,Larry,Casian,170.0,72.0,R,L,1990-09-09,1998-05-18,1990
6149,gilleto02,1962,7,2,USA,IL,Peoria,Tom,Gilles,185.0,73.0,R,R,1990-06-07,1990-06-08,1990
7835,hoovejo02,1962,12,22,USA,CA,Fresno,John,Hoover,190.0,74.0,R,R,1990-05-23,1990-05-25,1990
531,averyst01,1970,4,14,USA,MI,Trenton,Steve,Avery,180.0,76.0,L,L,1990-06-13,2003-07-20,1990
6257,goffje01,1964,4,12,USA,CA,San Rafael,Jerry,Goff,205.0,75.0,L,R,1990-05-15,1996-05-12,1990
12964,parkeri01,1963,3,20,USA,MO,Kansas City,Rick,Parker,185.0,72.0,R,R,1990-05-04,1996-08-30,1990
8060,hundlto01,1969,5,27,USA,VA,Martinsville,Todd,Hundley,170.0,71.0,B,R,1990-05-18,2003-09-27,1990
1225,berryse01,1966,3,22,USA,CA,Santa Monica,Sean,Berry,200.0,71.0,R,R,1990-09-17,2000-07-24,1990
13567,pooleji02,1966,4,28,USA,NY,Rochester,Jim,Poole,190.0,74.0,L,L,1990-06-15,2000-06-01,1990
16141,sprinst01,1961,2,11,USA,CA,Long Beach,Steve,Springer,190.0,72.0,R,R,1990-05-22,1992-08-25,1990
4974,ericksc01,1968,2,2,USA,CA,Long Beach,Scott,Erickson,220.0,76.0,R,R,1990-06-25,2006-06-08,1990
2160,burbada01,1966,7,7,USA,OH,Dayton,Dave,Burba,220.0,76.0,R,R,1990-09-08,2004-09-19,1990
3290,coninje01,1966,6,27,USA,WA,Tacoma,Jeff,Conine,205.0,73.0,R,R,1990-09-16,2007-09-30,1990
2601,carrch02,1967,8,10,USA,CA,San Bernardino,Chuck,Carr,155.0,70.0,B,R,1990-04-28,1997-09-27,1990
10658,martiti02,1967,12,7,USA,FL,Tampa,Tino,Martinez,205.0,74.0,L,R,1990-08-20,2005-10-02,1990
5128,fariepa01,1965,2,20,USA,CA,Berkeley,Paul,Faries,165.0,70.0,R,R,1990-09-06,1993-09-26,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,beckch02,1990,9,4,USA,GA,Commerce,Chris,Beck,225.0,75.0,R,R,2015-05-28,2015-05-28,2015
14393,roberke02,1988,3,9,USA,TN,Murfreesboro,Kenny,Roberts,200.0,73.0,L,L,2015-05-03,2015-10-03,2015
4276,diazel01,1990,11,17,Venezuela,Zulia,Maracaibo,Elias,Diaz,210.0,72.0,R,R,2015-09-12,2015-09-30,2015
4224,deshide02,1992,8,16,USA,GA,Gaston,Delino,DeShields,210.0,69.0,R,R,2015-04-08,2015-10-04,2015
17654,waldrky02,1991,11,26,USA,FL,Fort Myers,Kyle,Waldrop,215.0,74.0,L,L,2015-08-02,2015-08-02,2015
4204,depaujo02,1988,3,4,D.R.,Santo Domingo,Villa Mella,Jose,De Paula,170.0,73.0,R,L,2015-06-21,2015-06-21,2015
1061,bellaan01,1991,8,5,USA,CA,San Diego,Andrew,Bellatti,190.0,73.0,R,R,2015-05-09,2015-10-02,2015
4152,delosab01,1992,11,21,D.R.,Puerto Plata,Puerto Plata,Abel,De Los Santos,200.0,74.0,R,R,2015-07-21,2015-07-23,2015
14679,rossjo01,1993,5,21,USA,CA,Berkeley,Joe,Ross,205.0,76.0,R,R,2015-06-06,2015-09-24,2015
14571,rollida01,1989,12,21,USA,TX,Deberry,David,Rollins,210.0,73.0,L,L,2015-07-04,2015-09-30,2015
4468,dornda01,1984,7,20,USA,CA,San Dimas,Danny,Dorn,200.0,74.0,L,L,2015-04-21,2015-07-19,2015
14331,riverfe01,1991,7,5,Venezuela,Yaracuy,San Felipe,Felipe,Rivero,200.0,74.0,L,L,2015-04-17,2015-10-03,2015
4548,drakeol01,1987,1,13,USA,MA,Worcester,Oliver,Drake,215.0,76.0,R,R,2015-05-23,2015-10-03,2015
13954,ravinjo01,1988,1,21,USA,CA,West Hills,Josh,Ravin,230.0,76.0,R,R,2015-06-02,2015-07-25,2015
13978,reaco01,1990,7,1,USA,IA,Cascade,Colin,Rea,220.0,77.0,R,R,2015-08-11,2015-09-09,2015
13987,rearich01,1987,12,5,USA,GA,Pooler,Chris,Rearick,200.0,75.0,L,L,2015-04-12,2015-04-25,2015
4873,ellinbr02,1990,8,4,USA,FL,Gainesville,Brian,Ellington,195.0,76.0,R,R,2015-08-03,2015-10-03,2015
4846,eickhje01,1990,7,2,USA,IN,Evansville,Jerad,Eickhoff,240.0,76.0,R,R,2015-08-21,2015-10-01,2015
14016,reedch01,1990,5,20,United Kingdom,London,London,Chris,Reed,225.0,75.0,L,L,2015-08-01,2015-08-03,2015
14032,reedmi02,1992,11,18,USA,MN,Maplewood,Michael,Reed,190.0,72.0,R,R,2015-09-26,2015-10-04,2015
4812,edwarca01,1991,9,3,USA,SC,Newberry,Carl,Edwards,170.0,75.0,R,R,2015-09-07,2015-10-02,2015
14045,refsnro01,1991,3,26,South Korea,Seoul,Seoul,Rob,Refsnyder,195.0,72.0,R,R,2015-07-11,2015-10-03,2015
4752,easleed01,1985,12,21,USA,TN,Memphis,Ed,Easley,205.0,72.0,R,R,2015-05-29,2015-10-04,2015
4733,dykstal01,1987,5,21,USA,CA,San Diego,Allan,Dykstra,215.0,77.0,L,R,2015-04-08,2015-04-23,2015
4638,dullry01,1989,10,2,USA,NC,Winston-Salem,Ryan,Dull,175.0,70.0,R,R,2015-09-01,2015-10-04,2015
4622,duffyma02,1989,2,6,USA,MA,Boston,Matt,Duffy,215.0,75.0,R,R,2015-09-16,2015-10-03,2015
4610,duffety01,1990,12,27,USA,TX,Houston,Tyler,Duffey,220.0,75.0,R,R,2015-08-05,2015-10-01,2015
4592,drurybr01,1992,8,21,USA,OR,Grants Pass,Brandon,Drury,215.0,73.0,R,R,2015-09-01,2015-10-03,2015
804,barraky01,1990,5,23,USA,CA,Santa Clara,Kyle,Barraclough,225.0,75.0,R,R,2015-08-07,2015-10-01,2015
18845,zychto01,1990,8,7,USA,IL,Monee,Tony,Zych,190.0,75.0,R,R,2015-09-04,2015-10-03,2015